### ISSUE TITLE
Can you share your experience with fast-autoaugment

### ISSUE THREAD

**Issue by saigontrade88** [HanxunH/Unlearnable-Examples#18]
Hello,

Thanks you for sharing your good work. You showed in the Appendix, Table 3 that your class-wise and sample-wise noise is unstable when the model is trained with Fast AutoAugment. In the following question under the official implementation of the fast-autoaugment, there is some complaint about the incompatibility between RayX and Slurm. Can you help share how you run the fast-auto augment for your unlearnable example? Many thanks. 

https://github.com/kakaobrain/fast-autoaugment/issues/27

**Comment by HanxunH** [comment]
Hi,

It seems the issue is due to an augmentation search rather than applying the augmentation in training. I'm not aware of any fix. 

For running fast auto augment on unlearnable examples, have a look at the following:

https://github.com/HanxunH/Unlearnable-Examples/blob/28e1e417259ce5baf0d3e68d3408d9f8ecc3024f/dataset.py#L17

https://github.com/HanxunH/Unlearnable-Examples/blob/28e1e417259ce5baf0d3e68d3408d9f8ecc3024f/dataset.py#L117

**Comment by saigontrade88** [comment]
Many thanks for the prompt reply and useful information.
